<a href="https://colab.research.google.com/github/kigit2017/ModelPerformance/blob/main/ModelPerformance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import pandas as pd

In [33]:
data=pd.read_csv('/content/train.csv')

In [34]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [35]:
print(data.shape)

(1460, 81)

Data processing

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [37]:
data['SalePrice'].isna().sum()

0

include float and int columns only

In [38]:
df = data.select_dtypes(include=['int64','float64'])

In [39]:
df.shape

(1460, 38)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 38 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   OverallQual    1460 non-null   int64
 5   OverallCond    1460 non-null   int64
 6   YearBuilt      1460 non-null   int64
 7   YearRemodAdd   1460 non-null   int64
 8   MasVnrArea     1452 non-null   float64
 9   BsmtFinSF1     1460 non-null   int64
 10  BsmtFinSF2     1460 non-null   int64
 11  BsmtUnfSF      1460 non-null   int64
 12  TotalBsmtSF    1460 non-null   int64
 13  1stFlrSF       1460 non-null   int64
 14  2ndFlrSF       1460 non-null   int64
 15  LowQualFinSF   1460 non-null   int64
 16  GrLivArea      1460 non-null   int64
 17  BsmtFullBath   1460 non-null   int64
 18  BsmtHalfBath   1460 non-null   int64
 19  FullBath       1460 non-null   int64
 20  HalfBath       1460 non-null   int64
 21  BedroomAbvGr   1460 non-null   int64
 22  KitchenAbvGr   1460 non-null   int64
 23  TotRmsAbvGrd   1460 non-null   int64
 24  Fireplaces     1460 non-null   int64
 25  GarageYrBlt    1379 non-null   float64
 26  GarageCars     1460 non-null   int64
 27  GarageArea     1460 non-null   int64
 28  WoodDeckSF     1460 non-null   int64
 29  OpenPorchSF    1460 non-null   int64
 30  EnclosedPorch  1460 non-null   int64
 31  3SsnPorch      1460 non-null   int64
 32  ScreenPorch    1460 non-null   int64
 33  PoolArea       1460 non-null   int64
 34  MiscVal        1460 non-null   int64
 35  MoSold         1460 non-null   int64
 36  YrSold         1460 non-null   int64
 37  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35)
memory usage: 433.6 KB

In [41]:
#Missing values sum

In [42]:
miss_val=df.isna().sum()

Get columns with no missing values in a list

In [43]:
miss_val=miss_val[miss_val==0].sort_values(ascending=False)

In [44]:
li=list(miss_val.index)

In [45]:
df[li]

,Id,OpenPorchSF,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea,WoodDeckSF,EnclosedPorch,HalfBath,...,BsmtFinSF1,BsmtUnfSF,BsmtHalfBath,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,SalePrice
0,1,61,1,8,0,2,548,0,0,1,...,706,150,0,856,856,854,0,1710,1,208500
1,2,0,1,6,1,2,460,298,0,0,...,978,284,1,1262,1262,0,0,1262,0,181500
2,3,42,1,6,1,2,608,0,0,1,...,486,434,0,920,920,866,0,1786,1,223500
3,4,35,1,7,1,3,642,0,272,0,...,216,540,0,756,961,756,0,1717,1,140000
4,5,84,1,9,1,3,836,192,0,1,...,655,490,0,1145,1145,1053,0,2198,1,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,40,1,7,1,2,460,0,0,1,...,0,953,0,953,953,694,0,1647,0,175000
1456,1457,0,1,7,2,2,500,349,0,0,...,790,589,0,1542,2073,0,0,2073,1,210000
1457,1458,60,1,9,2,1,252,0,0,0,...,275,877,0,1152,1188,1152,0,2340,0,266500
1458,1459,0,1,5,0,1,240,366,112,0,...,49,0,0,1078,1078,0,0,1078,1,142125
1459,1460,68,1,6,0,1,276,736,0,1,...,830,136,0,1256,1256,0,0,1256,1,147500

Correlation of 'SalePrice' column, to remove columns with low values and keep stron  correlated values

In [46]:
df_corr= df[li].corr()

Get correlation of all Saleprice columns except the last columns'SalePrice'

In [47]:
df_sale= df_corr['SalePrice'][:-1]

In [48]:
df_sale

Id              -0.021917
OpenPorchSF      0.315856
KitchenAbvGr    -0.135907
TotRmsAbvGrd     0.533723
Fireplaces       0.466929
GarageCars       0.640409
GarageArea       0.623431
WoodDeckSF       0.324413
EnclosedPorch   -0.128578
HalfBath         0.284108
3SsnPorch        0.044584
ScreenPorch      0.111447
PoolArea         0.092404
MiscVal         -0.021190
MoSold           0.046432
YrSold          -0.028923
BedroomAbvGr     0.168213
FullBath         0.560664
MSSubClass      -0.084284
BsmtFinSF2      -0.011378
LotArea          0.263843
OverallQual      0.790982
OverallCond     -0.077856
YearBuilt        0.522897
YearRemodAdd     0.507101
BsmtFinSF1       0.386420
BsmtUnfSF        0.214479
BsmtHalfBath    -0.016844
TotalBsmtSF      0.613581
1stFlrSF         0.605852
2ndFlrSF         0.319334
LowQualFinSF    -0.025606
GrLivArea        0.708624
BsmtFullBath     0.227122
Name: SalePrice, dtype: float64

In [49]:
df_2= df_sale[df_sale>.5]

In [50]:
list(df_2.index)

['TotRmsAbvGrd',
 'GarageCars',
 'GarageArea',
 'FullBath',
 'OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 'TotalBsmtSF',
 '1stFlrSF',
 'GrLivArea']

In [51]:
columns = list(df_2.index)
columns
 #['LotFrontage','GarageYrBlt','MasVnrArea','BsmtHalfBath','BsmtFullBath','GarageArea','GarageCars','TotalBsmtSF',\                'BsmtUnfSF','BsmtFinSF2','BsmtFinSF1']

['TotRmsAbvGrd',
 'GarageCars',
 'GarageArea',
 'FullBath',
 'OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 'TotalBsmtSF',
 '1stFlrSF',
 'GrLivArea']

From df - Out of 38 we choose 10 columns from the list for evaluation.

In [52]:
df[columns].shape

(1460, 10)

In [53]:
X=df[columns]

In [54]:
X

,TotRmsAbvGrd,GarageCars,GarageArea,FullBath,OverallQual,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea
0,8,2,548,2,7,2003,2003,856,856,1710
1,6,2,460,2,6,1976,1976,1262,1262,1262
2,6,2,608,2,7,2001,2002,920,920,1786
3,7,3,642,1,7,1915,1970,756,961,1717
4,9,3,836,2,8,2000,2000,1145,1145,2198
...,...,...,...,...,...,...,...,...,...,...
1455,7,2,460,2,6,1999,2000,953,953,1647
1456,7,2,500,2,6,1978,1988,1542,2073,2073
1457,9,1,252,2,7,1941,2006,1152,1188,2340
1458,5,1,240,1,5,1950,1996,1078,1078,1078
1459,6,1,276,1,5,1965,1965,1256,1256,1256

In [55]:
y=df['SalePrice']

In [56]:
from sklearn.model_selection import train_test_split
train_X,test_X,train_y,test_y = train_test_split(X,y,test_size=.3,random_state=1)

In [57]:
#print(train_X.shape)
#print(train_y.head())
test_X

,TotRmsAbvGrd,GarageCars,GarageArea,FullBath,OverallQual,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea
258,7,2,564,2,7,2001,2001,963,963,1792
267,8,1,240,2,5,1939,1997,720,1052,2192
288,5,1,280,1,5,1967,1967,882,900,900
649,3,0,0,1,4,1970,1970,630,630,630
1233,6,2,531,1,5,1959,1959,1188,1188,1188
...,...,...,...,...,...,...,...,...,...,...
793,7,2,474,2,8,2007,2007,1496,1496,1496
631,6,2,627,2,8,2006,2006,1554,1554,1554
1172,5,2,625,2,7,2006,2007,625,625,1250
1167,7,2,472,2,6,2000,2000,959,959,1671
529,9,2,484,3,6,1957,1975,2035,2515,2515

In [58]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [66]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import math
lin = LinearRegression()
model= lin.fit(train_X,train_y)
y_pred = model.predict(test_X)
#print(y_pred)
#print(test_y)
#print("accuracy_score",accuracy_score(test_y,y_pred))
mse= (math.sqrt(mean_squared_error(y_pred,test_y)))
print("Mean Squared error", round(mse,2))

Mean Squared error 35946.97

In [69]:
#Mean absolute errot
MAPE= np.mean(abs((y_pred-test_y)/test_y)*100)
print("Mean absolute error",round(MAPE,2))

Mean absolute error 14.8

In [74]:
#R-Squared
from sklearn.metrics import  r2_score
r2_score = r2_score(y_pred,test_y)
print('R2 score:',round(r2_score,3))

R2 score: 0.733

In [81]:
#Adrjuste R2 score
#1- (1 - r2) * (N-1)/(N-p-1)
N=X.shape[0]

p=X.shape[1]

Adj_r2 = (1-r2_score) * ((N-1)/(N-p-1))
print("Adj r2score ",round(Adj_r2,3))

Adj r2score  0.268